#!/bin/sh

ME=$(basename "$0")
HEVERY_DIR="$(dirname $0)/hevery"
COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3
CLASSPATH="$HEVERY_DIR/bin/*:$HEVERY_DIR/libs/*"

java -cp $CLASSPATH com.dpforge.hevery.cli.Main $HEVERY_DIR $ME $COMMIT_MSG_FILE $COMMIT_SOURCE $SHA1